name: Deployment Pipeline

on:
  push:
    branches:
      - master

jobs: 
  deploy-python:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Deploy Python App
      run: |
        cd project/hello-python/
        python app.py
    
  deploy-node:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    
    - name: Deploy Node.js App
      run: |
        cd project/hello-node/
        npm install
        node app.js
